title: Public Org-Structure Database
description: Website for a public research database (GitHub Pages)
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
url: "https://OrganizationDesign.github.io"
baseurl: "/homepage"
owner_name: "John Eklund"
license_url: "https://creativecommons.org/licenses/by-nc/4.0/"
ack_source: "Albert, D., Eklund, J. C., & Tang, L. (2025). A new organizational structure database: Examining structure through top management team compositions. <em>Strategic Management Journal</em>, smj.70029. https://doi.org/10.1002/smj.70029"

